In [9]:
from IPython import embed
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import colors

from sklearn.naive_bayes import GaussianNB
from sklearn import datasets


iris = datasets.load_iris()
# Only take the first two features
X = iris.data[:, :2]
y = iris.target

x_min, x_max = X[:, 0].min() - .5, X[:, 0].max() + .5
y_min, y_max = X[:, 1].min() - .5, X[:, 1].max() + .5



In [15]:
X[:,1]

array([ 3.5,  3. ,  3.2,  3.1,  3.6,  3.9,  3.4,  3.4,  2.9,  3.1,  3.7,
        3.4,  3. ,  3. ,  4. ,  4.4,  3.9,  3.5,  3.8,  3.8,  3.4,  3.7,
        3.6,  3.3,  3.4,  3. ,  3.4,  3.5,  3.4,  3.2,  3.1,  3.4,  4.1,
        4.2,  3.1,  3.2,  3.5,  3.1,  3. ,  3.4,  3.5,  2.3,  3.2,  3.5,
        3.8,  3. ,  3.8,  3.2,  3.7,  3.3,  3.2,  3.2,  3.1,  2.3,  2.8,
        2.8,  3.3,  2.4,  2.9,  2.7,  2. ,  3. ,  2.2,  2.9,  2.9,  3.1,
        3. ,  2.7,  2.2,  2.5,  3.2,  2.8,  2.5,  2.8,  2.9,  3. ,  2.8,
        3. ,  2.9,  2.6,  2.4,  2.4,  2.7,  2.7,  3. ,  3.4,  3.1,  2.3,
        3. ,  2.5,  2.6,  3. ,  2.6,  2.3,  2.7,  3. ,  2.9,  2.9,  2.5,
        2.8,  3.3,  2.7,  3. ,  2.9,  3. ,  3. ,  2.5,  2.9,  2.5,  3.6,
        3.2,  2.7,  3. ,  2.5,  2.8,  3.2,  3. ,  3.8,  2.6,  2.2,  3.2,
        2.8,  2.8,  2.7,  3.3,  3.2,  2.8,  3. ,  2.8,  3. ,  2.8,  3.8,
        2.8,  2.8,  2.6,  3. ,  3.4,  3.1,  3. ,  3.1,  3.1,  3.1,  2.7,
        3.2,  3.3,  3. ,  2.5,  3. ,  3.4,  3. ])

In [4]:
# Fit the Naive Bayes classifier
gnb = GaussianNB()
gnb.fit(X, y)

# Classify a grid of points
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 30),
                     np.linspace(y_min, y_max, 30))
Z = gnb.predict_proba(np.c_[xx.ravel(), yy.ravel()])


In [17]:
np.c_[xx.ravel(), yy.ravel()]

array([[ 3.8       ,  1.5       ],
       [ 3.95862069,  1.5       ],
       [ 4.11724138,  1.5       ],
       ..., 
       [ 8.08275862,  4.9       ],
       [ 8.24137931,  4.9       ],
       [ 8.4       ,  4.9       ]])

In [5]:
xx.ravel()

array([ 3.8       ,  3.95862069,  4.11724138,  4.27586207,  4.43448276,
        4.59310345,  4.75172414,  4.91034483,  5.06896552,  5.22758621,
        5.3862069 ,  5.54482759,  5.70344828,  5.86206897,  6.02068966,
        6.17931034,  6.33793103,  6.49655172,  6.65517241,  6.8137931 ,
        6.97241379,  7.13103448,  7.28965517,  7.44827586,  7.60689655,
        7.76551724,  7.92413793,  8.08275862,  8.24137931,  8.4       ,
        3.8       ,  3.95862069,  4.11724138,  4.27586207,  4.43448276,
        4.59310345,  4.75172414,  4.91034483,  5.06896552,  5.22758621,
        5.3862069 ,  5.54482759,  5.70344828,  5.86206897,  6.02068966,
        6.17931034,  6.33793103,  6.49655172,  6.65517241,  6.8137931 ,
        6.97241379,  7.13103448,  7.28965517,  7.44827586,  7.60689655,
        7.76551724,  7.92413793,  8.08275862,  8.24137931,  8.4       ,
        3.8       ,  3.95862069,  4.11724138,  4.27586207,  4.43448276,
        4.59310345,  4.75172414,  4.91034483,  5.06896552,  5.22

In [ ]:
Z1 = Z[:, 1].reshape(xx.shape)
Z2 = Z[:, 2].reshape(xx.shape)

# Plot
fig = plt.figure(figsize=(5, 3.75))
ax = fig.add_subplot(111)
ax.scatter(X[:, 0], X[:, 1], c=y, cmap=plt.cm.Set1,
            edgecolor='k')
# Swap signs to make the contour dashed (MPL default)
ax.contour(xx, yy, -Z1, [-0.5], colors='k')
ax.contour(xx, yy, -Z2, [-0.5], colors='k')

# Plot formatting
ax.set_xlabel('Sepal length')
ax.set_ylabel('Sepal width')
ax.set_title('sklearn decision boundary')
ax.set_xlim(x_min, x_max)
ax.set_ylim(y_min, y_max)
ax.set_xticks(())
ax.set_yticks(())

plt.tight_layout()
fig.savefig('iris_sklearn.png', bbox_inches='tight')
plt.show()

In [6]:
xx.ravel()[3]

4.2758620689655169

In [8]:
len(yy.ravel())

900